import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),PORT=process.env.PORT||3000;const users=new Map(),sessions=new Map(),battles=new Map();let uid=1,bid=1;
const types=['swordsman','archer','cavalry'];const names={swordsman:'شمشیرزن',archer:'کماندار',cavalry:'سواره‌نظام'};
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>({s,h:crypto.scryptSync(p,s,64).toString('hex')});const check=(p,u)=>{try{return crypto.timingSafeEqual(Buffer.from(crypto.scryptSync(p,u.s,64).toString('hex'),'hex'),Buffer.from(u.h,'hex'))}catch{return false}};
const send=(r,c,d)=>{r.writeHead(c,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});r.end(JSON.stringify(d))};
async function body(q){let s='';for await(const c of q)s+=c;return s?JSON.parse(s):{}}function auth(q){return sessions.get((q.headers.authorization||'').replace('Bearer ',''))}function xy(c){return[c%10,Math.floor(c/10)]}function dist(a,b){let A=xy(a),B=xy(b);return Math.hypot(A[0]-B[0],A[1]-B[1])}function pub(u){return{id:u.id,name:u.name,cell:u.cell,army:u.army,castleLevel:u.castleLevel}}
function place(rows,cell,side){let [cx,cy]=xy(cell),used=new Set(),out=[];for(const r of rows){for(let n=0;n<100;n++){let x=cx+(side==='defender'?1:-1)+(n%3),y=cy+Math.floor(n/3),k=x+','+y;if(!used.has(k)){used.add(k);out.push([r.type,r.count,r.castle,side,x,y]);break}}}return out}
function manageBattle(b){if(!b||b.status!=='traveling'||Date.now()<b.arrivalAt)return false;b.status='managed';b.managedAt=Date.now();return true}
async function api(q,r,u,url){if(url.pathname==='/api/world')return send(r,200,{self:pub(u),players:[...users.values()].filter(x=>x.id!==u.id).map(pub),battles:[...battles.values()].filter(b=>b.attackerId===u.id||b.defenderId===u.id)});if(url.pathname==='/api/attack'||url.pathname==='/api/defense'){let d=await body(q),t=users.get(String(d.targetId));if(!t||t.id===u.id)return send(r,400,{error:'قلعه مقصد نامعتبر است'});let rows=(Array.isArray(d.units)?d.units:[]).filter(x=>types.includes(x.type)&&Number(x.count)>0).map(x=>({type:x.type,count:Math.min(Math.floor(Number(x.count)),u.army[x.type]||0)})).filter(x=>x.count);if(!rows.length)return send(r,400,{error:'نیرو انتخاب نشده'});rows.forEach(x=>u.army[x.type]-=x.count);let mode=url.pathname.endsWith('attack')?'attack':'defense',sec=Math.max(5,Math.round(dist(u.cell,t.cell)*10)),b={id:String(bid++),attackerId:u.id,defenderId:t.id,targetCell:t.cell,mode,createdAt:Date.now(),arrivalAt:Date.now()+sec*1000,status:'traveling',army:place(rows,t.cell,mode==='attack'?'attacker':'defender')};battles.set(b.id,b);return send(r,200,{battle:b,user:pub(u)})}if(url.pathname==='/api/battle/manage'){let d=await body(q),b=battles.get(String(d.battleId));if(!b)return send(r,404,{error:'نبرد پیدا نشد'});if(b.attackerId!==u.id&&b.defenderId!==u.id)return send(r,403,{error:'دسترسی ندارید'});if(!manageBattle(b))return send(r,409,{error:'هنوز زمان رسیدن تمام نشده'});return send(r,200,{ok:true,battle:b})}if(url.pathname==='/api/me')return send(r,200,{user:pub(u)});send(r,404,{error:'not found'})}
const server=http.createServer(async(q,r)=>{if(q.method==='OPTIONS')return send(r,204,{});let url=new URL(q.url,'http://x');if(url.pathname==='/api/register'&&q.method==='POST'){let d=await body(q),n=String(d.name||'').trim(),p=String(d.password||'');if(n.length<2||p.length<2)return send(r,400,{error:'نام کاربری و رمز نامعتبر است'});if([...users.values()].some(x=>x.name.toLowerCase()===n.toLowerCase()))return send(r,409,{error:'نام کاربری تکراری است'});let h=hash(p),cell=0,used=new Set([...users.values()].map(x=>x.cell));while(used.has(cell))cell++;let u={id:String(uid++),name:n,s:h.s,h:h.h,cell,castleLevel:1,army:{swordsman:100,archer:100,cavalry:100}};users.set(u.id,u);let t=crypto.randomBytes(24).toString('hex');sessions.set(t,u);return send(r,200,{token:t,user:pub(u)})}if(q.method==='POST'&&url.pathname==='/api/login'){let d=await body(q),u=[...users.values()].find(x=>x.name.toLowerCase()===String(d.name||'').trim().toLowerCase());if(!u||!check(String(d.password||''),u))return send(r,401,{error:'ورود ناموفق'});let t=crypto.randomBytes(24).toString('hex');sessions.set(t,u);return send(r,200,{token:t,user:pub(u)})}if(url.pathname.startsWith('/api/')){let u=auth(q);if(!u)return send(r,401,{error:'نیاز به ورود'});return api(q,r,u,url)}let file=path.join(root,url.pathname==='/'?'index.html':url.pathname);if(!file.startsWith(root))return r.writeHead(403).end();fs.readFile(file,(e,d)=>{if(e)return r.writeHead(404).end();let ext=path.extname(file),ct={'.html':'text/html; charset=utf-8','.png':'image/png','.css':'text/css','.js':'text/javascript'}[ext]||'application/octet-stream';r.writeHead(200,{'Content-Type':ct});r.end(d)})});server.listen(PORT,()=>console.log('Fresh game on '+PORT));
